### ISSUE TITLE
TypeError: this.report is not a function

### ISSUE THREAD

**Issue by D219** [Atinux/schema-inspector#58]
I do not understand why, but using `exec` to make a custom check.  
Specifically, trying to report the error just raise a TypeError.

Exemple code:

    'use strict';

    const schema = {
        test: {
            type: 'object',
            strict: true,
            optional: false,
            properties: {
                a: {
                    type: 'string',
                    exec: (schema, post) => {
                        try {
                            JSON.parse(post);
                        } catch (e) {
                            this.report('Not serialized JSON');
                        }
                    }
                }
            }
        }
    };

    const inspector = require('schema-inspector');

    let test = {
            valid: {
                a: JSON.stringify({foo: 'bar'})
            },
            invalid: {
                a: 'invalid'
            }
        };

    console.log(inspector.validate(schema.test, test.valid));
    console.log(inspector.validate(schema.test, test.invalid));

Result in:

```
C:\Users\_\Documents\GIT\test\foobar.js:15
    this.report('Not serialized JSON');
         ^

TypeError: this.report is not a function
    at Validation.exec (C:\Users\_\Documents\GIT\test\foobar.js:15:34)
    at C:\Users\_\Documents\GIT\test\node_modules\schema-inspector\lib\schema-inspector.js:429:11
    at Array.forEach (native)
    at Validation.exec (C:\Users\_\Documents\GIT\test\node_modules\schema-inspector\lib\schema-inspector.js:427:63)
    at Validation.<anonymous> (C:\Users\_\Documents\GIT\test\node_modules\schema-inspector\lib\schema-inspector.js:635:12)
    at Array.forEach (native)
    at Validation._validate (C:\Users\_\Documents\GIT\test\node_modules\schema-inspector\lib\schema-inspector.js:633:21)
    at Validation.properties (C:\Users\_\Documents\GIT\test\node_modules\schema-inspector\lib\schema-inspector.js:457:10)
    at Validation.<anonymous> (C:\Users\_\Documents\GIT\test\node_modules\schema-inspector\lib\schema-inspector.js:635:12)
    at Array.forEach (native)
```

**Comment by Atinux** [comment]
You should not use the `=>` syntax since it keeps the parent scope.

Use exec like this:

```js
exec: function (schema, post) {
  try {
     JSON.parse(post);
  } catch (e) {
     this.report('Not serialized JSON');
  }
}
```
